/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Config {
	app: App
	database: Database
	jwt: Jwt
	redis: Redis
}
export interface App {
	port: number
	host: string
	redirect_url?: string
}
export interface Database {
	url: string
}
export interface Jwt {
	secret: string
}
export interface Redis {
	url: string
	username?: string
	password?: string
}
