/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Config {
	app: App
	database: Database
	jwt: Jwt
	redis: Redis
	short_code: ShortCode
	cache: Cache
	certificates: Certificates
	rate_limiter: RateLimiter
}
export interface App {
	port: number
	host: string
	redirect_url?: string
}
export interface Database {
	url: string
}
export interface Jwt {
	secret: string
	access_token_ttl: number
	refresh_token_ttl: number
}
export interface Redis {
	url: string
	username?: string
	password?: string
	blacklist_prefix: string
	user_tokens_prefix: string
}
export interface ShortCode {
	length: number
	max_length: number
	max_attempts: number
}
export interface Cache {
	max_size: number
	ttl: number
}
export interface Certificates {
	cert_path: string
	key_path: string
}
export interface RateLimiter {
	window_ms: number
	limit: number
	redis_prefix: string
}
